config/routes.rb
Rails.application.routes.draw do
root 'posts#index', as: 'home'
get 'about'=>'pages#about', as: 'about'
resources :posts


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
      @heading = 'Страничка про нас!'
      @text = 'Немного текста'
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @poster = Post.all
  end

  def new
    @post = Post.new
  end
  def edit
    @post = Post.find(params[:id])
  end
  def show
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
<h5 class="my-0 mr-md-auto font-weight-normal">Ебало на ноль</h5>
<nav class="my-2 my-md-0 mr-md-3">
  <span class="btn btn-outline-primary"><%=link_to "главная страница", home_path %></span>
  <span class="btn btn-outline-primary"><%=link_to "Про нас", about_path %></span>

</nav>
<span class="btn btn-outline-primary"><%=link_to "Добавление статьи", new_post_path %></span>
</div>
<div class="container">
  <%= yield %>
</div>
  </body>
</html>

app/views/pages/about.html.erb
<h1> <%= @heading %></h1>
<p><%=@text%> </p>

app/views/posts/edit.html.erb
<h2>EDIT new post</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
<% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
        <% end %>
  <% end %>
<p>
  Название <br>
  <%=  f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
  Текст статьи <br>
  <%=  f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
  <%=  f.submit({:class=>'btn btn-success'})%>
</p>
<%end%>

app/views/posts/index.html.erb
<h3>главная страница</h3>

  <% @poster.each do |post| %>
  <div class="alert alert-light">
      <h3><%= post.title %></h3>
      <p><%= post.body %></p>
      <%= link_to 'Show', post_path(post), :class=>'btn btn-outline-primary' %>
      </div>
  <% end %>

app/views/posts/new.html.erb
<h2>ADD new post</h2>
<%= form_for :post, url: posts_path do |f| %>
<% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
        <% end %>
  <% end %>
<p>
  Название <br>
  <%=  f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
  Текст статьи <br>
  <%=  f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
  <%=  f.submit({:class=>'btn btn-success'})%>
</p>
<%end%>

app/views/posts/show.html.erb
<h2><%=@post.title%></h2>
<p><%=@post.body%></p>

<%= link_to "Редактировать", edit_post_path(@post), :class=>'btn btn-warning'%>
<%= link_to "Удалить", post_path(@post), method: :delete, :class=>'btn btn-danger'%>